<?php

/**
 * @file
 * Adds support for sending SMS messages using the Mobily.ws gateway.
 */

module_load_include('inc', 'sms_mobilyws', 'convertToUnicode');

/**
 * Implementation of hook_gateway_info().
 */
function sms_mobilyws_gateway_info() {
  return array(
    'mobilyws' => array(
      'name' => 'Mobily.ws',
      'configure form' => 'sms_mobilyws_admin_form',
      'send' => 'sms_mobilyws_send',
      'send form' => 'sms_mobilyws_send_form',
    ),
  );
}

/**
 * Configuration form for gateway module.
 */
function sms_mobilyws_admin_form($configuration) {

  $form['sms_mobilyws_status'] = array(
    '#type' => 'textfield',
    '#title' => t('Mobily.ws Serivce Status'),
    '#default_value' => _get_sms_status(),
    '#description' => t('!Mobily.ws serivce availability.', array(
      '!Mobily.ws' => '<a target="_blank" href="http://mobily.ws">Mobily.ws</a>',
    )),
    '#size' => 30,
    '#disabled' => TRUE,
    '#maxlength' => 64,
    '#required' => FALSE,
  );

  $form['sms_mobilyws_balance'] = array(
    '#type' => 'textfield',
    '#title' => t('Your Balance'),
    '#default_value' => sms_mobilyws_balance(),
    '#description' => t('The current balance of your !Mobily.ws gateway account.', array(
      '!Mobily.ws' => '<a target="_blank" href="http://mobily.ws">Mobily.ws</a>',
    )),
    '#size' => 30,
    '#disabled' => TRUE,
    '#maxlength' => 64,
    '#required' => FALSE,
  );

  $form['sms_mobilyws_sender'] = array(
    '#type' => 'textfield',
    '#title' => t('Sender'),
    '#description' => t('The sender name of your !Mobily.ws gateway account.', array(
      '!Mobily.ws' => '<a target="_blank" href="http://mobily.ws">Mobily.ws</a>',
    )),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => $configuration['sms_mobilyws_sender'] ?: '',
  );

  $form['sms_mobilyws_user'] = array(
    '#type' => 'textfield',
    '#title' => t('User'),
    '#description' => t('The username of your !Mobily.ws gateway account.', array(
      '!Mobily.ws' => '<a target="_blank" href="http://mobily.ws">Mobily.ws</a>',
    )),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => $configuration['sms_mobilyws_user'] ?: '',
  );

  $form['sms_mobilyws_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#description' => t('The password of your !Mobily.ws gateway account.', array(
      '!Mobily.ws' => '<a target="_blank" href="http://mobily.ws">Mobily.ws</a>',
    )),
    '#size' => 30,
    '#maxlength' => 64,
    '#default_value' => $configuration['sms_mobilyws_password'] ?: '',
  );

  return $form;
}

/**
 * Callback for sending messages.
 */
function sms_mobilyws_send($number, $message, $options) {

  $gateway = sms_gateways('gateway', 'mobilyws');
  $config = $gateway['configuration'];

  $url = "www.mobily.ws/api/msgSend.php";
  $application_type = "24";
  $msg = convertToUnicode($message);
  $sendr = $config['sms_mobilyws_sender'];
  $sender = urlencode($sendr);

  $string_to_post = "mobile=" . $config['sms_mobilyws_user'] . "&password=" . $config['sms_mobilyws_password'] . "&numbers=" . $options['country'] . $number . "&sender=" . $sender . "&msg=" . $msg . "&applicationType=" . $application_type;

  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_HEADER, 0);
  curl_setopt($ch, CURLOPT_TIMEOUT, 5);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $string_to_post);

  $result = curl_exec($ch);

  return $result;
}


/**
 * Get the balance of your account.
 */
function sms_mobilyws_balance() {

  $gateway = sms_gateways('gateway', 'mobilyws');
  $config = $gateway['configuration'];

  $url = "http://www.mobily.ws/api/balance.php";
  $string_to_post = "mobile=" . $config['sms_mobilyws_user'] . "&password=" . $config['sms_mobilyws_password'];
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_HEADER, 0);
  curl_setopt($ch, CURLOPT_TIMEOUT, 5);
  curl_setopt($ch, CURLOPT_POST, 1);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $string_to_post);
  $result = curl_exec($ch);

  return $result;
}

/**
 * Get the Availablity of your account.
 */
function _get_sms_status() {

  global $send_status;
  $context_options['http'] = array(
    'method' => 'GET',
    'max_redirects' => 0,
    'protocol_version' => 1.0,
    'timeout' => 10,
    'ignore_errors' => TRUE,
  );

  $context_resouce  = stream_context_create($context_options);
  $url = "http://www.mobily.ws/api/sendStatus.php";
  $array_result = file($url, FILE_IGNORE_NEW_LINES, $context_resouce);
  $result = $array_result[0];

  // if($viewResult)
  $result = trim(($result), $send_status);
  if ($result == 1) {
    return t('Available');
  }
  else {
    return t('Unavailable');
  }
}

/**
 * Returns custom additions to be added to the send forms.
 */
function sms_mobilyws_send_form() {
  $form['country'] = array(
    '#type' => 'select',
    '#title' => t('Country'),
    '#multiple' => FALSE,
    '#options' => sms_country_codes(),
    '#default_value' => -1,
  );

  return $form;
}
